import { Inter } from 'next/font/google'
import './globals.css'
import React from 'react'
import '@fortawesome/fontawesome-free/css/all.css'
import 'bootstrap/dist/css/bootstrap.css'
import './admin/admin.css'
import 'bootstrap-icons/font/bootstrap-icons.css'
import { GlobalProvider } from './globalContext'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'E-Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='min-w-full min-h-full'>
      <GlobalProvider>
        <body className={inter.className}>{children}</body>
      </GlobalProvider>
    </html>
  )
}